#!/bin/sh
# to restore the input settings after a pacman update

#default keymap
setxkbmap -layout tr -option caps:swapescape

#writing speed
xset r rate 300 50

#disable bell volume
xset -b

#fix mouse accel
mouse_id=$(xinput --list --short | grep -m 1 "Logitech G304" | sed 's,^.*id=,,g' | cut -c -2)
accel_id=$(xinput -list-props $mouse_id | grep -m 1 "Accel Profile Enabled"| sed 's,^.*(,,;s,).*,,')
xinput -set-prop $mouse_id $accel_id 0, 1

